name: "Setup Transcrypt"
description: "Installs the Transcypt CLI"

runs:
  using: "composite"
  steps:
    - name: Install Transcrypt cli
      shell: bash
      run: |
        mkdir -p $HOME/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        wget https://raw.githubusercontent.com/elasticdog/transcrypt/016b2e4b31951be5ea96233d8d2badef9c9836b6/transcrypt -O "$HOME/.local/bin/transcrypt"
        chmod +x "$HOME/.local/bin/transcrypt"
