# Generated by Django 5.0.4 on 2024-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_ecobalyseuser_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecobalyseuser",
            name="organization",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Organization"
            ),
        ),
    ]
