name: "Build a release"
description: "Create the dist files for a specific version"

inputs:
  tag:
    description: 'The tag we want to create the release for'
    required: true
  # @FIX: this should not be required?
  commit_sha:
    description: 'The commit of the tag'
    required: true
  encryption_key:
    description: 'The key used to encypt the detailed processes'
    required: true
  private_ssh_key:
    description: 'The private ssh key used to clone the detailed impacts'
    required: true
  ecobalyse_data_dir:
    description: 'The path to the ecobalyse dir containing the detailed impacts'
    required: false
    default: "./ecobalyse-private"
outputs:
  dist-archive:
    description: "Dist archive file path"
    value: ${{ steps.create-dist-archive.outputs.dist-archive }}


runs:
  using: "composite"
  steps:

    - uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: 'npm'

    - name: Install Node dependencies
      shell: bash
      run: npm ci --prefer-offline --no-audit

    - name: Clone the detailed impacts
      shell: bash
      run: |
        eval `ssh-agent -s`
        ssh-add - <<< '${{ inputs.private_ssh_key }}'
        git clone git@github.com:MTES-MCT/ecobalyse-private.git

    - name: Build app
      shell: bash
      env:
        # Specify the created SHA to correctly update version.json
        # @FIX: this should not be requiered when creating a tagged version
        SOURCE_VERSION: ${{ inputs.commit_sha }}
        TAG: ${{ inputs.tag }}
        ECOBALYSE_DATA_DIR: ${{ inputs.ecobalyse_data_dir }}
      run: |
        npm run build:standalone-app

    - name: Encrypt the impacts files
      shell: bash
      env:
        ENCRYPTION_KEY: ${{ inputs.encryption_key }}
        ECOBALYSE_DATA_DIR: ${{ inputs.ecobalyse_data_dir }}
      run : |
        # We include the encrypted detailed processes with the dist
        # so that people with the encryption key could later on use the app with the exact
        # files it was using on production
        npm run encrypt $ECOBALYSE_DATA_DIR/data/textile/processes_impacts.json dist/processes_impacts_textile.json.enc
        npm run encrypt $ECOBALYSE_DATA_DIR/data/food/processes_impacts.json dist/processes_impacts_food.json.enc

    - name: Generate dist archive
      shell: bash
      id: create-dist-archive
      run: |
        tar czvf ${{ inputs.tag }}-dist.tar.gz dist
        echo "dist-archive=${{ inputs.tag }}-dist.tar.gz" >> $GITHUB_OUTPUT
