version: 2

updates:
  # master (current version)
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
    cooldown:
      semver-major-days: 90 # it’s the maximum allowed by dependabot, 3 months
    groups: # Group updates by patch type in the same PR
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "uv"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
    cooldown:
      semver-major-days: 90 # it’s the maximum allowed by dependabot, 3 months
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  # stable/textile (regulatory version)
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "stable/textile"
    schedule:
      interval: "monthly"
    cooldown:
      semver-major-days: 90 # it’s the maximum allowed by dependabot, 3 months
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
