version: 2
max-commits-for-hook: 500
secret:
  ignored-paths:
    - 'data/backend/authentication/migrations/0003_alter_ecobalyseuser_token.py'
  ignored-matches:
    - name: authentication
      match: 0002_ecobalyseuser_token
