repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
      exclude: (svg|icomoon)
    - id: trailing-whitespace
    - id: no-commit-to-branch
      name: "don't commit to main"
      args: [--branch, main]

  - repo: local
    hooks:
      - id: app-prettier
        name: run prettier
        language: system
        files: ^.*$
        exclude: data
        types_or: [javascript, json]
        entry: |
          bash -c 'npm --prefix . run fix:prettier -- "${@}"'

      - id: app-ruff-check
        name: run ruff check
        language: system
        files: ^.*$
        types_or: [python]
        entry: |
          bash -c 'npm --prefix . run fix:ruff:check "${@}"' --

      - id: app-ty-check
        name: run ty check
        language: system
        files: ^.*$
        types_or: [python]
        entry: |
          bash -c 'npm --prefix . run fix:ty:check "${@}"' --

      - id: app-ruff-format
        name: run ruff format
        language: system
        files: ^.*$
        types_or: [python]
        entry: |
          bash -c 'npm --prefix . run fix:ruff:format "${@}"' --

      - id: app-elm-format
        name: run elm-format
        language: system
        files: ^.*$
        exclude: data
        types_or: [elm]
        entry: |
          bash -c 'npm --prefix . run fix:elm-format "${@}"' --

      - id: fix-json
        name: run JSON formatter
        language: system
        types_or: [json]
        entry: |
          bash -c '
            to_format=$(bin/filter_ignored.sh "$@")
            [ -n "$to_format" ] && uv run bin/json_formatter.py --fix $to_format
            exit 0
          ' --

      - id: check-json-schemas
        name: check json schemas
        language: system
        files: ^data/public/data/processes.*\.json$
        types_or: [json]
        entry: |
          bash -c 'just check-processes'
