module Transport exposing (..)

-- import Data.Country exposing (..)
-- import Data.Transport as Transport
-- import Expect
-- import Test exposing (..)
-- suite : Test
-- suite =
--     describe "Data.Country"
--         [ describe "getDistance"
--             [ test "should retrieve distance between two countries" <|
--                 \_ ->
--                     Transport.getDistance France China |> Expect.equal 21548
--             , test "should retrieve distance between two swapped countries" <|
--                 \_ ->
--                     Transport.getDistance China France |> Expect.equal 21548
--             , test "should fallback to 0 when unknown distance" <|
--                 \_ ->
--                     Transport.getDistance Greece Italy |> Expect.equal 0
--             ]
--         ]
