import json
import os
from typing import List, Optional

import orjson

from common import activities_processes_sort_key, remove_detailed_impacts
from common.base_ingredient import infer_base_ingredient
from common.export import export_json
from ecobalyse_data.bw.search import cached_search_one
from ecobalyse_data.export.complements import compute_forest_complement
from ecobalyse_data.export.land_occupation import compute_land_occupation_batch
from ecobalyse_data.export.utils import get_metadata_for_scope
from ecobalyse_data.logging import logger
from models.process import (
    GENERIC_SCOPES,
    IngredientMetadata,
    ProcessGeneric,
    Scope,
)


def _build_variant_metadata(
    variant: dict,
    activity: dict,
    food_variant: Optional[dict],
    ecs_by_alias: dict,
) -> Optional[dict]:
    """Build the metadata block for a variant, omitting cross-domain nulls.

    - Wood variants get `forestManagement` and `complements.forest` only.
    - Food variants get `ingredient` plus ECS keys in `complements`. Vegetal
      variants keep `permanentPasture` as null (within-domain
      structural nulls, mirroring ingredients.json).
    - Entries with no applicable metadata return None.
    """
    metadata: dict = {}

    forest_management = variant.get("forestManagement")
    complements: dict = {}
    if forest_management is not None:
        metadata["forestManagement"] = forest_management
        complements["forest"] = compute_forest_complement(
            forest_management,
            activity.get("landOccupation"),
        )

    if food_variant is not None:
        metadata["ingredient"] = IngredientMetadata(
            base_ingredient=infer_base_ingredient(food_variant["alias"]),
            crop_group=food_variant.get("cropGroup"),
            default_origin=food_variant["defaultOrigin"],
            density=food_variant["ingredientDensity"],
            inedible_part=food_variant["inediblePart"],
            raw_to_cooked_ratio=food_variant["rawToCookedRatio"],
            scenario=food_variant.get("scenario"),
            transport_cooling=food_variant["transportCooling"],
            process_id=activity["id"],
        ).model_dump(by_alias=True)

        ecs = ecs_by_alias.get(food_variant["alias"])
        if ecs:
            for key in (
                "cropDiversity",
                "hedges",
                "plotSize",
                "permanentPasture",
            ):
                complements[key] = ecs.get(key)

    if complements:
        metadata["complements"] = complements

    return metadata or None


def compute_processes_generic(
    activities: List[dict],
    processes_impacts_path: str,
    cpu_count: int = 1,
    ecosystemic_factors_path: Optional[str] = None,
    feed_file_path: Optional[str] = None,
    raw_to_transformed_file_path: Optional[str] = None,
) -> List[dict]:
    """Compute ProcessGeneric dicts with metadata enrichment.

    Merges process impacts with forest complement metadata and, for food
    ingredients, ingredient-specific metadata + ecosystemic service complements.

    Reads from processes_legacy_impacts_full.json (unfiltered) generated by the `processes-legacy` export.
    """
    if not os.path.exists(processes_impacts_path):
        raise FileNotFoundError(
            f"{processes_impacts_path} not found. "
            "Run 'just export-all' first to generate it."
        )

    with open(processes_impacts_path, "rb") as f:
        processes_list = orjson.loads(f.read())
    processes_by_id = {p["id"]: p for p in processes_list}

    food_activities = [a for a in activities if get_metadata_for_scope(a, "food")]
    has_food = bool(food_activities)
    need_ecs_inputs = has_food and all(
        p is not None
        for p in (
            ecosystemic_factors_path,
            feed_file_path,
            raw_to_transformed_file_path,
        )
    )

    ecs_by_alias: dict = {}
    if has_food:
        # Lazy import to avoid pulling matplotlib unless we actually need food logic
        from ecobalyse_data.export.food import (
            add_land_occupations as add_food_land_occupations,
        )
        from ecobalyse_data.export.food import (
            compute_es_for_ingredients,
            load_ecosystemic_dic,
        )

        food_activities = add_food_land_occupations(food_activities)
        food_by_id = {a["id"]: a for a in food_activities}
        activities = [food_by_id.get(a["id"], a) for a in activities]

        if need_ecs_inputs:
            ecosystemic_factors = load_ecosystemic_dic(ecosystemic_factors_path)
            with open(feed_file_path, "r") as f:
                feed_file_content = json.load(f)
            with open(raw_to_transformed_file_path, "r") as f:
                raw_to_transformed = json.load(f)
            ecs_by_alias = compute_es_for_ingredients(
                food_activities,
                ecosystemic_factors,
                feed_file_content,
                raw_to_transformed,
            )

    activities_needing_land = []
    for activity in activities:
        for metadata in activity.get("metadata", []):
            if "forestManagement" in metadata:
                activities_needing_land.append(activity)
                break

    if activities_needing_land:
        activities_needing_land = add_land_occupations(activities_needing_land)
        land_by_id = {a["id"]: a for a in activities_needing_land}
        activities = [land_by_id.get(a["id"], a) for a in activities]

    generic_dicts = []
    for activity in activities:
        process = processes_by_id.get(activity["id"])
        if not process:
            raise ValueError(
                f"Process not found for activity {activity.get('displayName')} "
                f"(id: {activity['id']})"
            )

        food_variants_by_id = {
            v["id"]: v for v in get_metadata_for_scope(activity, "food")
        }

        for variant in activity["metadata"]:
            metadata_out = _build_variant_metadata(
                variant=variant,
                activity=activity,
                food_variant=food_variants_by_id.get(variant["id"]),
                ecs_by_alias=ecs_by_alias,
            )

            food_variant = food_variants_by_id.get(variant["id"])
            land_occupation = (
                food_variant.get("landOccupation")
                if food_variant is not None
                and food_variant.get("landOccupation") is not None
                else activity.get("landOccupation")
            )

            entry = ProcessGeneric(
                activity_name=process["activityName"],
                alias=variant.get("alias"),
                categories=process["categories"],
                comment=process.get("comment", ""),
                display_name=variant.get(
                    "displayName", activity.get("displayName", "")
                ),
                elec_mj=process.get("elecMJ", 0),
                heat_mj=process.get("heatMJ", 0),
                id=variant["id"],
                impacts=process["impacts"],
                land_occupation=land_occupation,
                location=process.get("location"),
                mass_per_unit=process.get("massPerUnit"),
                metadata=None,
                scopes=[
                    Scope(s)
                    for s in variant.get("scopes", [])
                    if Scope(s) in GENERIC_SCOPES
                ],
                source=process["source"],
                unit=process.get("unit"),
                qty_variation_ratio=process.get("qtyVariationRatio", 1),
                visible=variant.get("visible", True),
            )
            entry_dict = entry.model_dump(by_alias=True)
            entry_dict["metadata"] = metadata_out
            generic_dicts.append(entry_dict)

    generic_dicts.sort(key=activities_processes_sort_key)

    return generic_dicts


def activities_to_processes_generic_json(
    activities: List[dict],
    processes_impacts_path: str,
    ecs_output_paths: List[str],
    impacts_output_paths: List[str],
    cpu_count: int = 1,
    ecosystemic_factors_path: Optional[str] = None,
    feed_file_path: Optional[str] = None,
    raw_to_transformed_file_path: Optional[str] = None,
) -> List[dict]:
    """Export object processes to ProcessGeneric json files."""
    generic_dicts = compute_processes_generic(
        activities,
        processes_impacts_path,
        cpu_count,
        ecosystemic_factors_path=ecosystemic_factors_path,
        feed_file_path=feed_file_path,
        raw_to_transformed_file_path=raw_to_transformed_file_path,
    )

    for path in impacts_output_paths:
        export_json(generic_dicts, path)
        logger.info(f"Exported {len(generic_dicts)} generic processes to {path}")

    without_detailed_impacts = remove_detailed_impacts(generic_dicts)
    for path in ecs_output_paths:
        export_json(without_detailed_impacts, path)
        logger.info(
            f"Exported {len(without_detailed_impacts)} generic processes without detailed impacts to {path}"
        )

    return generic_dicts


def add_land_occupations(activities: List[dict]) -> List[dict]:
    todo = [a for a in activities if "landOccupation" not in a]
    bw_by_eco_id = {
        a["id"]: cached_search_one(
            a.get("source"), a.get("activityName"), location=a.get("location")
        )
        for a in todo
    }
    scores = compute_land_occupation_batch(list(bw_by_eco_id.values()))
    for activity in todo:
        activity["landOccupation"] = scores[bw_by_eco_id[activity["id"]].id]
    return activities
