import os
from pathlib import Path

import orjson
import pytest
from app.domain.processes.schemas import Category

pytestmark = pytest.mark.anyio


here = Path(__file__).parent


# Be sure that the file generated by the data pipeline doesn’t contain invalid categories values
# if this test fails, consider adding the new value to the Category enum
async def test_process_categories() -> None:
    with open(os.path.join(here, "../../../public/data/processes.json"), "rb") as file:
        json_data = orjson.loads(file.read())
        possible_categories = [member.value for member in Category]

        for process in json_data:
            for category in process["categories"]:
                assert category in possible_categories
