# Generated by Django 5.0.3 on 2024-03-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecobalyseuser",
            name="terms_of_use",
            field=models.BooleanField(default=False),
        ),
    ]
