# Generated by Django 5.0.3 on 2024-03-28 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_ecobalyseuser_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecobalyseuser",
            name="token",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=36, verbose_name="TOKEN"
            ),
        ),
    ]
