# type: ignore
"""Store component as JSON

Revision ID: 21f0598992ca
Revises: bcba8b753777
Create Date: 2026-06-03 10:52:31.277357

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
)
from alembic import op
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    pass

__all__ = [
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = "21f0598992ca"
down_revision = "bcba8b753777"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("process_element_transform")
    op.drop_table("element")
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "value",
                sa.JSON()
                .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
                .with_variant(sa.ORA_JSONB(), "oracle")
                .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
                nullable=True,
            )
        )
        batch_op.drop_column("name")
        batch_op.drop_column("scopes")

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("comment", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "scopes",
                postgresql.ARRAY(
                    postgresql.ENUM(
                        "food", "food2", "object", "textile", "veli", name="scope"
                    )
                ),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.drop_column("value")

    op.create_table(
        "process_element_transform",
        sa.Column("process_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("element_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("position", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["element_id"],
            ["element.id"],
            name=op.f("fk_process_element_transform_element_id_element"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["process_id"],
            ["process.id"],
            name=op.f("fk_process_element_transform_process_id_process"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "process_id", "element_id", name=op.f("pk_process_element_transform")
        ),
    )
    op.create_table(
        "element",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "material_process_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("component_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("sa_orm_sentinel", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["component.id"],
            name=op.f("fk_element_component_id_component"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["material_process_id"],
            ["process.id"],
            name=op.f("fk_element_material_process_id_process"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_element")),
    )
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
