# type: ignore
"""Add last_login

Revision ID: 497ff53f5f65
Revises: 884ac9f3654f
Create Date: 2026-05-04 15:34:05.368674

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
)
from alembic import op
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    pass

__all__ = [
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = "497ff53f5f65"
down_revision = "884ac9f3654f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_login_at", sa.DateTimeUTC(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.drop_column("last_login_at")

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""
    op.execute("""
      UPDATE user_account
      SET last_login_at=subquery.max_updated_date
      FROM (SELECT sub_user.id as acc_id, GREATEST(sub_user.updated_at, token.last_accessed_at, token.created_at) AS max_updated_date from user_account as sub_user left join token on sub_user.id=token.user_id) AS subquery
      WHERE user_account.id=subquery.acc_id""")


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
