import functools
import json
import sys
from enum import StrEnum
from pathlib import Path, PurePosixPath
from typing import List, Optional

import bw2data
import bw2io
from bw2io.strategies.generic import link_iterable_by_fields
from bw2io.utils import activity_hash

from common import biosphere
from common.bw.simapro_json import SimaProJsonImporter, export_zipped_csv_to_json
from config import settings
from ecobalyse_data import s3
from ecobalyse_data.bw.search import cached_search_one
from ecobalyse_data.logging import logger


class ActivityFrom(StrEnum):
    SCRATCH = "from_scratch"
    EXISTING = "from_existing"


class ExchangeType(StrEnum):
    TECHNOSPHERE = "technosphere"
    BIOSPHERE = "biosphere"


def setup_project(
    setup_biosphere=True,
):
    biosphere_name = settings.bw.BIOSPHERE
    bw2data.projects.set_current(settings.bw.PROJECT)
    if setup_biosphere:
        bw2data.preferences["biosphere_database"] = biosphere_name

        if biosphere_name in bw2data.databases:
            logger.info(
                f"-> Biosphere database {biosphere_name} already present, no setup is needed, skipping."
            )
            return

        biosphere.create_ecospold_biosphere(
            dbname=biosphere_name,
            filepath=s3.get_file(
                settings.dbfiles.BIOSPHERE_FLOWS, settings.dbfiles.BIOSPHERE_FLOWS_MD5
            ),
        )

        biosphere.create_biosphere_lcia_methods(
            filepath=s3.get_file(
                settings.dbfiles.BIOSPHERE_LCIA, settings.dbfiles.BIOSPHERE_LCIA_MD5
            ),
        )

    add_missing_substances(settings.bw.PROJECT, biosphere_name)

    bw2io.create_core_migrations()


def link_technosphere_by_activity_hash_ref_product(
    db, external_db_name: Optional[str] = None, fields: Optional[List[str]] = None
):
    """
    This is a custom version of `bw2io.strategies.generic.link_technosphere_by_activity_hash`

    It adds the check for "processwithreferenceproduct" that was added in https://github.com/brightway-lca/brightway2-data/blob/main/CHANGES.md#40dev57-2024-10-03
    and avoid breaking the linking as processes are now imported with the default type "processwithreferenceproduct"
    """

    TECHNOSPHERE_TYPES = {"technosphere", "substitution", "production"}
    if external_db_name is not None:
        other = (
            obj
            for obj in bw2data.Database(external_db_name)
            if obj.get("type", "process") == "process"
            or obj.get("type") == "processwithreferenceproduct"
        )
        internal = False
    else:
        other = None
        internal = True
    return link_iterable_by_fields(
        db, other, internal=internal, kind=TECHNOSPHERE_TYPES, fields=fields
    )


def search_activity(activity_dict: dict, default_db: str | None = None):
    """Search for an activity using either a string or dict specification.

    Args:
        activity_dict: dict with keys:
                  - name (required): activity name
                  - database (optional): database name (uses default_db if not provided)
                  - location (optional): location code
                  - code (optional): specific activity code/UUID
        default_db: Default database name if not specified

    Returns:
        The found activity
    """
    if isinstance(activity_dict, dict):
        db_name = activity_dict.get("database", default_db)
        if db_name is None:
            raise ValueError("No database specified in activity dict or default_db")
        activity_name = activity_dict["name"]
        location = activity_dict.get("location")
        code = activity_dict.get("code")
        categories = activity_dict.get("categories")
        unit = activity_dict.get("unit")

        result = cached_search_one(
            db_name,
            activity_name,
            location=location,
            code=code,
            categories=tuple(categories) if categories else None,
            unit=unit,
        )
        return result
    else:
        raise ValueError("Activity must be a dict")


def create_activity(
    dbname, new_activity_name, base_activity=None, unit="kilogram", location=None
):
    """Creates a new activity by copying a base activity or from nothing. Returns the created activity"""

    if base_activity:
        data = base_activity.as_dict().copy()
        del data["code"]
        # Id should be autogenerated or BW will throw an error
        # `id` must be created automatically, but `id=137934742532190208` given
        if "id" in data:
            del data["id"]
        data["name"] = new_activity_name
        data["System description"] = "Ecobalyse"
        data["database"] = "Ecobalyse"
        # see https://github.com/brightway-lca/brightway2-data/blob/main/CHANGES.md#40dev57-2024-10-03
        data["type"] = "processwithreferenceproduct"
        if location is not None:
            data["location"] = location
        code = activity_hash(data)
        new_activity = base_activity.copy(code, **data)
    else:
        data = {
            "production amount": 1,
            "unit": unit,
            # see https://github.com/brightway-lca/brightway2-data/blob/main/CHANGES.md#40dev57-2024-10-03
            "type": "processwithreferenceproduct",
            "comment": "",
            "name": new_activity_name,
            "System description": "Ecobalyse",
            "location": location,
        }
        code = activity_hash(data)
        new_activity = bw2data.Database(dbname).new_activity(code, **data)
        new_activity["code"] = code
    new_activity["Process identifier"] = code
    new_activity.save()
    logger.debug(f"Created activity {new_activity}")
    return new_activity


def add_created_activities(created_activities_db, activities_to_create):
    """
    Once the agribalyse database has been imported, add to the database the new activities defined in `ACTIVITIES_TO_CREATE.json`.
    """
    with open(activities_to_create, "r") as f:
        activities_data = json.load(f)

    bw2data.Database(created_activities_db).register()

    for activity_data in activities_data:
        logger.debug(
            f"-> Creating activity {activity_data.get('activityCreationType')} '{activity_data.get('alias')}'"
        )
        if activity_data.get("activityCreationType") == ActivityFrom.SCRATCH:
            add_activity_from_scratch(activity_data, created_activities_db)
            logger.debug("-")
        if activity_data.get("activityCreationType") == ActivityFrom.EXISTING:
            add_activity_from_existing(activity_data, created_activities_db)
            logger.debug("-")


def add_activity_from_scratch(activity_data, dbname):
    """Add to the database dbname a new activity created from scratch

    Example : the "diesel, B7" activity is created from scratch with the following exchanges
    defined in activities_to_create.json

    "exchanges": [
      {
        {
          "name": "Carbon dioxide, fossil",
          "code": "349b29d1-3e58-4c66-98b9-9d1a076efd2e",
          "database": "biosphere3"
        },
        "amount": 2.19
      },
      {
        {
          "name": "Carbon monoxide, fossil",
          "code": "6edcc2df-88a3-48e1-83d8-ffc38d31c35b",
          "database": "biosphere3"
        },
        "amount": 0.014
      },
     ...
    """
    unit = activity_data.get("unit", "kilogram")
    activity_from_scratch = create_activity(
        dbname,
        f"{activity_data['newName']}",
        unit=unit,
        location=activity_data.get("location"),
    )

    for exchange_item in activity_data["exchanges"]:
        amount = exchange_item["amount"]
        activity_add = search_activity(exchange_item, activity_data["database"])
        new_exchange(activity_from_scratch, activity_add, amount)

    activity_from_scratch.save()


def delete_exchange(activity, activity_to_delete, amount=False):
    """Deletes an exchange from an activity."""
    if amount:
        for exchange in activity.exchanges():
            if (
                exchange.input["name"] == activity_to_delete["name"]
                and exchange["amount"] == amount
            ):
                exchange.delete()
                logger.debug(f"Deleted {exchange}")
                return

    else:
        for exchange in activity.exchanges():
            if exchange.input["name"] == activity_to_delete["name"]:
                exchange.delete()
                logger.debug(f"Deleted {exchange}")
                return
    raise ValueError(f"Did not find exchange {activity_to_delete}. No exchange deleted")


def get_exchange_type(activity: dict) -> ExchangeType:
    """Get the type of an exchange based on the activity"""
    if activity.get("database") == "biosphere3":
        return ExchangeType.BIOSPHERE
    return ExchangeType.TECHNOSPHERE


def new_exchange(activity, new_activity, new_amount=None, activity_to_copy_from=None):
    """Create a new exchange. If an activity_to_copy_from is provided, the amount is copied from this activity. Otherwise, the amount is new_amount.

    activity: the activity to which the new exchange is added
    new_activity: the new exchange will link to this new_activity
    new_amount: the amount of the new exchange
    activity_to_copy_from: the activity from which the amount is copied
    """
    assert new_amount is not None or activity_to_copy_from is not None, (
        "No amount or activity to copy from provided"
    )
    if new_amount is None and activity_to_copy_from is not None:
        for exchange in list(activity.exchanges()):
            if exchange.input["name"] == activity_to_copy_from["name"]:
                new_amount = exchange["amount"]
                break
        else:
            raise ValueError(
                f"Exchange to duplicate from :{activity_to_copy_from} not found. No exchange added"
            )

    new_exchange = activity.new_exchange(
        name=new_activity["name"],
        input=new_activity,
        amount=new_amount,
        type=get_exchange_type(new_activity),
        unit=new_activity["unit"],
        comment="",
    )
    new_exchange.save()
    logger.debug(f"Exchange {new_activity} added with amount: {new_amount}")


def replace_activities(new_activity, activity_data, base_db):
    """Replace all activities in activity_data["replace"] with variants of these activities"""
    # replace is now an array of objects: [{"from": {...}, "to": {...}}, ...]
    for replacement in activity_data["replacementPlan"].get("replace", []):
        activity_to_be_replaced = search_activity(replacement["from"], base_db)
        activity_replacing = search_activity(replacement["to"], base_db)
        new_exchange(
            new_activity,
            activity_replacing,
            activity_to_copy_from=activity_to_be_replaced,
        )
        delete_exchange(new_activity, activity_to_be_replaced)


def add_activity_from_existing(activity_data, created_activities_db):
    """Add to the database a new activity : the variant of an activity

    Example : ingredient flour-organic is not in agribalyse so it is created at this step. It's a
    variant of activity flour
    """
    default_db = activity_data["database"]
    # Example : the flour-conventional
    # existingActivity is now an object: {"name": "...", "database": "..."}
    existing_activity = search_activity(activity_data["existingActivity"], default_db)

    # create a new  activity
    # Example: this is where we create the flour-organic activity
    new_activity = create_activity(
        created_activities_db,
        f"{activity_data['newName']}",
        existing_activity,
        location=activity_data.get("location"),
    )

    if "delete" in activity_data:
        # delete is now an array of exchange objects: [{"name": "..."}, ...]
        for exchange_spec in activity_data["delete"]:
            for exchange in new_activity.exchanges():
                if all(
                    [exchange.get(spec[0]) == spec[1] for spec in exchange_spec.items()]
                ):
                    exchange.delete()
                    logger.debug(f"Deleted {exchange}")

    if "exchanges" in activity_data:
        for exchange_item in activity_data["exchanges"]:
            amount = exchange_item["amount"]
            activity_add = search_activity(exchange_item, activity_data["database"])
            new_exchange(new_activity, activity_add, amount)
        new_activity.save()

    if "replacementPlan" in activity_data:
        # if the activity has no upstream path, we can directly replace the seed activity with the seed
        #  activity variant
        if not activity_data["replacementPlan"]["upstreamPath"]:
            replace_activities(new_activity, activity_data, activity_data["database"])

        # else we have to iterate through the upstream path and create a new variant activity for each upstream activity

        # Example: for flour-organic we have to dig through the upstream process `global milling process` and
        #  replace the wheat activity with the wheat-organic activity
        else:
            for i, upstream_activity_data in enumerate(
                activity_data["replacementPlan"]["upstreamPath"]
            ):
                upstream_activity = search_activity(upstream_activity_data, default_db)

                # create a new upstream_activity_variant
                upstream_activity_variant = create_activity(
                    created_activities_db,
                    f"{upstream_activity['name']} {{{{{activity_data['alias']}}}}}",
                    upstream_activity,
                )
                upstream_activity_variant.save()

                # link the newly created upstream_activity_variant to the parent activity_variant
                new_exchange(
                    new_activity,
                    upstream_activity_variant,
                    activity_to_copy_from=upstream_activity,
                )
                delete_exchange(new_activity, upstream_activity)

                # for the last upstream activity: apply replacements and add any exchanges
                if i == len(activity_data["replacementPlan"]["upstreamPath"]) - 1:
                    replace_activities(
                        upstream_activity_variant,
                        activity_data,
                        upstream_activity["database"],
                    )
                    if "exchanges" in activity_data["replacementPlan"]:
                        for exchange_item in activity_data["replacementPlan"][
                            "exchanges"
                        ]:
                            amount = exchange_item["amount"]
                            activity_add = search_activity(
                                exchange_item, upstream_activity["database"]
                            )
                            new_exchange(
                                upstream_activity_variant, activity_add, amount
                            )
                        upstream_activity_variant.save()

                # update the activity_variant (parent activity)
                new_activity = upstream_activity_variant


def add_unlinked_flows_to_biosphere_database(
    database,
    biosphere_name=None,
    fields={"name", "unit", "categories"},
) -> None:
    biosphere_name = biosphere_name or bw2data.config.biosphere
    assert biosphere_name in bw2data.databases, (
        "{} biosphere database not found".format(biosphere_name)
    )

    bio = bw2data.Database(biosphere_name)

    def reformat(exc):
        dct = {key: value for key, value in list(exc.items()) if key in fields}
        dct.update(
            type="emission",
            exchanges=[],
            code=activity_hash(dct),
            database=biosphere_name,
        )
        return dct

    new_data = [
        reformat(exc)
        for ds in database.data
        for exc in ds.get("exchanges", [])
        if exc["type"] == "biosphere" and not exc.get("input")
    ]

    # Dictionary eliminate duplicates
    # first load the new data with activity_hash
    data = {(biosphere_name, exc["code"]): exc for exc in new_data}
    # then deduplicate/overwrite them with original data
    # still using the activity_hash as a key but the uuis as internal code
    data.update(
        {(biosphere_name, activity_hash(exc)): exc for exc in bio.load().values()}
    )
    # then reconstruct data with the uuid
    data = {(biosphere_name, exc["code"]): exc for exc in data.values()}
    bio.write(data)

    database.apply_strategy(
        functools.partial(
            link_iterable_by_fields,
            other=(obj for obj in bw2data.Database(biosphere_name)),
            edge_kinds=["biosphere"],
        ),
    )


def import_simapro_csv(
    database_s3_key: str,
    database_md5: str,
    dbname,
    external_db=None,
    biosphere="biosphere3",
    migrations=[],
    strategies=[],
):
    """
    Import the s3 file `database_s3_key` into a database named `dbname` and apply the provided brightway `migrations`.
    """
    logger.info(f"🟢 Importing {database_s3_key} into {dbname}")
    assert PurePosixPath(database_s3_key).suffixes[-2:] in [
        [".CSV", ".zip"],
        [".csv", ".zip"],
    ], (
        "⛔ the LCA databases should be zipped CSV files, and have a `.csv.zip` extension"
    )

    local_path = s3.get_file(database_s3_key, database_md5)
    json_datapath = local_path.parent / Path(local_path.stem).with_suffix(
        f".{database_md5}.json"
    )

    if not json_datapath.is_file():
        logger.info(
            f"🟠 converting to JSON (that will only be done once) => {json_datapath}"
        )
        export_zipped_csv_to_json(local_path, json_datapath, db_name=dbname)
        assert json_datapath.is_file()

    database = SimaProJsonImporter(str(json_datapath), dbname, normalize_biosphere=True)

    logger.debug("Applying migrations")
    # Apply provided migrations
    for migration in migrations:
        logger.debug(f"-> Applying custom migration: {migration['description']}")
        bw2io.Migration(migration["name"]).write(
            migration["data"],
            description=migration["description"],
        )
        database.migrate(migration["name"])
    database.statistics()

    logger.debug("Applying strategies")
    database.strategies = strategies

    database.apply_strategies()
    database.statistics()

    # try to link remaining unlinked technosphere activities
    database.apply_strategy(
        functools.partial(
            link_technosphere_by_activity_hash_ref_product,
            fields=("name", "unit", "location"),
        )
    )
    database.apply_strategy(
        functools.partial(
            link_technosphere_by_activity_hash_ref_product, fields=("name", "unit")
        )
    )
    database.apply_strategy(
        functools.partial(
            link_technosphere_by_activity_hash_ref_product,
            external_db_name=external_db,
            fields=("name", "unit", "location"),
        )
    )
    database.apply_strategy(
        functools.partial(
            link_technosphere_by_activity_hash_ref_product,
            external_db_name=external_db,
            fields=("name", "unit"),
        )
    )
    database.apply_strategy(
        functools.partial(
            link_iterable_by_fields,
            other=bw2data.Database(biosphere),
            kind="biosphere",
        ),
    )

    database.statistics()

    logger.debug("Adding unlinked flows and activities")
    # comment to enable stopping on unlinked activities and creating an excel file
    add_unlinked_flows_to_biosphere_database(database, biosphere)
    database.add_unlinked_activities()

    # stop if there are unlinked activities
    if len(list(database.unlinked)):
        database.write_excel(only_unlinked=True)
        logger.error(
            "Look at the above excel file, there are still unlinked activities. Consider improving the migrations"
        )
        sys.exit(1)
    database.statistics()

    dsdict = {ds["code"]: ds for ds in database.data}
    database.data = list(dsdict.values())

    database.statistics()
    bw2data.Database(biosphere).register()
    database.write_database()

    logger.info(f"🟢 Finished importing {database_s3_key}")


def add_missing_substances(project, biosphere):
    """Two additional substances provided by ecoinvent and that seem to be in 3.9.2 but not in 3.9.1"""
    substances = {
        "a35f0a31-fe92-56db-b0ca-cc878d270fde": {
            "name": "Hydrogen cyanide",
            "synonyms": ["Hydrocyanic acid", "Formic anammonide", "Formonitrile"],
            "categories": ("air",),
            "unit": "kilogram",
            "CAS Number": "000074-90-8",
            "formula": "HCN",
        },
        "ea53a165-9f19-54f2-90a3-3e5c7a05051f": {
            "name": "N,N-Dimethylformamide",
            "synonyms": ["Formamide, N,N-dimethyl-", "Dimethyl formamide"],
            "categories": ("air",),
            "unit": "kilogram",
            "CAS Number": "000068-12-2",
            "formula": "C3H7NO",
        },
    }
    bw2data.projects.set_current(project)
    bio = bw2data.Database(biosphere)
    for code, activity in substances.items():
        if not [flow for flow in bio if flow["code"] == code]:
            bio.new_activity(code, **activity)
