#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if code is formatted
if ! npm run format:check ; then
  echo "Code is not formatted. Run 'npm run format:json' to format before committing."
  exit 1
fi
