name: Create release archive

env:
  TRANSCRYPT_KEY: ${{ secrets.TRANSCRYPT_KEY }}
  ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

on:
  workflow_dispatch:
  pull_request:

jobs:
  create_release_archive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Transcrypt
        uses: ./.github/actions/transcrypt-cli

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Create the dist archive for this release
        id: create-release
        uses: ./.github/actions/create-release
        with:
          sha: ${{ github.sha }}
          tag: ${{ github.sha }}

      - run: echo ✅ "$ARCHIVE_PATH" created!
        shell: bash
        env:
          ARCHIVE_PATH: ${{ steps.create-release.outputs.archive-path }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-archive
          path: ${{ steps.create-release.outputs.archive-path }}
