# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: End to end tests

env:
  NODE_ENV: test
  TRANSCRYPT_KEY: ${{ secrets.TRANSCRYPT_KEY }}
  ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
  BACKEND_API_URL: http://localhost:1234/backend
  ENABLE_FOOD_SECTION: "True"
  ENABLE_OBJECTS_SECTION: "True"
  EMAIL_SERVER_HOST: localhost
  EMAIL_SERVER_PORT: 1025
  EMAIL_SERVER_USE_TLS: false
on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Install transcrypt
      run: |
        mkdir -p $HOME/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        wget https://raw.githubusercontent.com/elasticdog/transcrypt/016b2e4b31951be5ea96233d8d2badef9c9836b6/transcrypt -O "$HOME/.local/bin/transcrypt"
        chmod +x "$HOME/.local/bin/transcrypt"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache node_modules
      id: cache-node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('package.json', 'package-lock.json') }}

    - name: Cache ~/.elm
      # see https://docs.microsoft.com/en-us/answers/questions/510640/deploy-elm-app-to-azure-static-website-from-github.html
      uses: actions/cache@v4
      with:
        path: ~/.elm
        key: elm-cache-${{ hashFiles('elm.json') }}
        restore-keys: elm-cache-

    - name: Install Node dependencies
      run: npm ci --prefer-offline --no-audit

    - name: Install Playwright Browsers
      run: npx playwright install chromium --with-deps

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        python-version: ${{ matrix.python-version }}

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        ## limits ssh access and adds the ssh public key for the user which triggered the workflow
        limit-access-to-actor: true
        ## limits ssh access and adds the ssh public keys of the listed GitHub users
        limit-access-to-users: vjousse

    - name: Run Playwright tests
      run: NODE_ENV=test npm run test:e2e

    - name: Upload test articacts
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 3
