name: Rate-limiting tests

env:
  NODE_ENV: test
  TRANSCRYPT_KEY: ${{ secrets.TRANSCRYPT_KEY }}
  ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
  ENABLE_FOOD_SECTION: "True"
  ENABLE_OBJECTS_SECTION: "True"
  ENABLE_VELI_SECTION: "True"
  EMAIL_SERVER_HOST: localhost
  EMAIL_SERVER_PORT: 1025
  EMAIL_SERVER_USE_TLS: false
  MATOMO_HOST: ""
  SENTRY_DSN: ""
on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Install transcrypt
      run: |
        mkdir -p $HOME/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        wget https://raw.githubusercontent.com/elasticdog/transcrypt/016b2e4b31951be5ea96233d8d2badef9c9836b6/transcrypt -O "$HOME/.local/bin/transcrypt"
        chmod +x "$HOME/.local/bin/transcrypt"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache node_modules
      id: cache-node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('package.json', 'package-lock.json') }}

    - name: Cache ~/.elm
      # see https://docs.microsoft.com/en-us/answers/questions/510640/deploy-elm-app-to-azure-static-website-from-github.html
      uses: actions/cache@v4
      with:
        path: ~/.elm
        key: elm-cache-${{ hashFiles('elm.json') }}
        restore-keys: elm-cache-

    - name: Install Node dependencies
      run: npm ci --prefer-offline --no-audit

    - name: Build app
      run: npm run build --if-present

    - name: Run rate-limiting tests
      run: npm run test:rate-limiting
