name: Deploy Review App

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  deploy-review-app:
    name: Deploy Review App
    runs-on: ubuntu-latest
    # We want this to run if Node.js CI passes, regardless of ecobalyse-data-sync
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v4

      - name: Install Scalingo CLI
        uses: ./.github/actions/scalingo-cli

      - name: Add scalingo to known hosts
        run: echo "KNOWN_HOSTS=$(ssh-keyscan -H ssh.osc-fr1.scalingo.com)" >> $GITHUB_ENV

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ env.KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Deploy Review App
        env:
          SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
          SCALINGO_APP: ecobalyse
          SCALINGO_REGION: ${{ secrets.SCALINGO_REGION }}
        run: |
          scalingo --app $SCALINGO_APP review-app create
