name: Deploy Review App

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-review-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/scalingo-cli
      - env:
          SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
          SCALINGO_APP: ecobalyse
          SCALINGO_REGION: ${{ secrets.SCALINGO_REGION }}
        run: scalingo --app $SCALINGO_APP review-app create
