name: Deploy Review App

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]
  workflow_dispatch:

jobs:
  deploy-review-app:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/scalingo-cli
      - env:
          SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
          SCALINGO_APP: ecobalyse
          SCALINGO_REGION: ${{ secrets.SCALINGO_REGION }}
        run: scalingo --app $SCALINGO_APP review-app create
