name: Deploy Review App

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-review-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
          SCALINGO_APP: ecobalyse
        run: |
          curl -H "Accept: application/json" \
               -H "Content-Type: application/json" \
               -H "Authorization: Bearer $SCALINGO_API_TOKEN" \
               -X POST https://api.osc-fr1.scalingo.com/v1/apps/$SCALINGO_APP/scm_repo_link/manual_review_app \
               -d "{\"pull_request_id\": ${{ github.event.pull_request.number }}}"
